version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    command: bash -c "npm run start"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always